### PR TITLE
Implemented database command

### PR DESCRIPTION
**Pull request by halilkocaoz**
1. Clear command moved to under database command (database -c --force)
2. Open command added to open local database folder (database -o)
3. Show command added to show local database path(database -s)

I tested opening folder command on Windows, Ubuntu. These are working, but I couldn't test on the MacOS. Could you please take care of it for MacOS?

Except for this, I did not edit to readme.md file because of my English. Normally, I know that I must do it for each feature, but as I said.

### CODE REVIEW

**Comment by halilkocaoz** [comment]
I tested the 'database -o' command on Ubuntu, it is not working. I will try to fix that.

ubuntu

**Comment by halilkocaoz** [comment]
I started to think that these commands can broke verb system of TaskCore.
Like: 'database -c --force -o -s' clear, open and show commands are usable at the same time. 

If you do you think that this will be a problem, I can re-write. Thanks

**Comment by tarikguney** [comment]
@halilkocaoz I will take a look at the code once I get a chance. However, supporting this pattern `database -c --force -o -s` will increase the complexity. If you could separate them out into their own verbs, I'd appreciate that.

**Comment by halilkocaoz** [comment]
I blocked clear command but If you don't have time to read these, nevermind. Tomorrow, I might re-pr about that.

**Pull request closed without merging**
